#!/usr/bin/env bash
# Writes ckad-cluster.yaml from ckad-cluster.template.yaml, substituting the values in lab.env.
# kind reads its config file literally and does not expand variables, hence the generation step.
set -euo pipefail
cd "$(dirname "$0")/.."

# Exported so envsubst, a separate process, can read them.
set -a
source ./lab.env
set +a

{
  echo "# GENERATED by scripts/generate-kind-config.sh. Do not edit:"
  echo "# change values in lab.env (structure in ckad-cluster.template.yaml) and rerun the script."
  grep -v '^##' ckad-cluster.template.yaml | envsubst
} > ckad-cluster.yaml

echo "wrote ckad-cluster.yaml"
