#!/usr/bin/env bash
# Generates ckad-cluster.yaml (the kind cluster config) from ckad-cluster.template.yaml, filling the
# ${VARIABLE} placeholders with the values in lab.env. kind itself does not expand variables in its
# config file, hence the generation step.
#   scripts/generate-kind-config.sh           write ckad-cluster.yaml
#   scripts/generate-kind-config.sh --check   write nothing; exit 1 if ckad-cluster.yaml is out of date
set -euo pipefail
cd "$(dirname "$0")/.."

TEMPLATE=ckad-cluster.template.yaml
OUTPUT=ckad-cluster.yaml
VARIABLES=(CLUSTER_NAME NODE_IMAGE POD_SUBNET SERVICE_SUBNET INGRESS_HTTP_HOST_PORT INGRESS_HTTPS_HOST_PORT)

command -v envsubst >/dev/null || { echo "envsubst not found; install it with: brew install gettext" >&2; exit 1; }

# set -a exports every variable lab.env assigns, so envsubst (a separate process) can read them.
set -a
source ./lab.env
set +a

for name in "${VARIABLES[@]}"; do
  [[ -n "${!name:-}" ]] || { echo "${name} is not set in lab.env" >&2; exit 1; }
done

# Only the listed variables are substituted; any other "$" in the template stays as written.
shell_format=$(printf '${%s} ' "${VARIABLES[@]}")
generated=$(
  printf '%s\n' \
    "# GENERATED by scripts/generate-kind-config.sh from ${TEMPLATE} and lab.env. Do not edit:" \
    "# change values in lab.env (structure in ${TEMPLATE}) and rerun the script."
  grep -v '^##' "$TEMPLATE" | envsubst "$shell_format"
)

if grep -q '\${' <<<"$generated"; then
  echo "unfilled placeholder(s) in ${TEMPLATE}; add the variable to VARIABLES and lab.env:" >&2
  grep -n '\${' <<<"$generated" >&2
  exit 1
fi

if [[ "${1:-}" == "--check" ]]; then
  if [[ -f "$OUTPUT" && "$generated" == "$(cat "$OUTPUT")" ]]; then
    echo "${OUTPUT} is up to date with lab.env"
  else
    echo "${OUTPUT} is out of date with lab.env; run scripts/generate-kind-config.sh" >&2
    diff <(printf '%s\n' "$generated") "$OUTPUT" >&2 || true
    exit 1
  fi
else
  printf '%s\n' "$generated" > "$OUTPUT"
  echo "wrote ${OUTPUT}"
fi
